name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run package
      - run: npm run make
      - name: Archive Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: out/make/**/*.exe

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install RPM build tools
        run: sudo apt-get update && sudo apt-get install -y rpm
      - run: npm ci
      - run: npm run package
      - run: npm run make
      - name: Archive Linux Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-packages
          path: |
            out/make/**/*.deb
            out/make/**/*.rpm

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: windows-exe
      - uses: actions/download-artifact@v3
        with:
          name: linux-packages
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            windows-exe/**/*.exe
            linux-packages/**/*.deb
            linux-packages/**/*.rpm
          makeLatest: true